med/crm/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('<str:pk>/tasks/', views.tasks, name='tasks'),
    path('<str:pk>/storage/', views.storage, name='storage'),
    path('<str:pk>/partners/', views.partners, name='partners'),
    path('<str:pk>/partners/<int:id>/', views.clients, name='clients'),
    path('<str:pk>/', views.clinic, name='clinic'),
    path('', views.index, name='home'),
]

med/med/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('crm.urls')),
]

med/crm/models.py
from django.db import models

from django.contrib.auth.models import User


class Item(models.Model):
    name = models.CharField('Название', primary_key = True, max_length=80)
    amount = models.IntegerField('Количество', default=0)
    used_today = models.IntegerField('Использовано', default=0)
    clinic = models.ForeignKey(User, on_delete=models.CASCADE)
    
    
    def set_amount(self, num):
        self.used_today = 0
        self.amount = num
        
    def add_amount(self, num):
        self.used_today = 0
        self.amount += num
    
    def remove_amount(self, num):
        self.used_today += num
        self.amount -= num


class Partner(models.Model):
    id = models.IntegerField('ID', primary_key = True)
    name = models.CharField('Имя', max_length=25)
    surname = models.CharField('Фамилия', max_length=25)
    payed = models.IntegerField('Прибыль', default=0)
    bill = models.IntegerField('Долг', default=0)
    client_num = models.IntegerField('Количество клиентов', default=0)
    clinic = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    
    
    def pay(self, num):
        self.payed += num
        self.bill -= num
        if self.bill < 0:
            self.bill = 0
    
    def add_bill(self, num):
        self.bill += num
    

class Client(models.Model):
    id = models.IntegerField('ID', primary_key = True)
    name = models.CharField('Имя', max_length=25)
    surname = models.CharField('Фамилия', max_length=25)
    isAdult = models.BooleanField('Взрослый', default=True)
    payed = models.IntegerField('Оплачено', default=0)
    bill = models.IntegerField('Долг', default=0)
    partner = models.ForeignKey(Partner, on_delete=models.CASCADE)
    
    def pay(self, num):
        self.payed += num
        self.bill -= num
        if self.bill < 0:
            self.bill = 0
    
    def add_bill(self, num):
        self.bill += num
    

class Task(models.Model):
    name = models.CharField('Название', primary_key = True, max_length=80)
    desc = models.TextField('Количество')
    made = models.BooleanField('Выполнено', default=True)
    clinic = models.ForeignKey(User, on_delete=models.CASCADE)
    
    
    def complete(self):
        self.made = True
        

med/crm/forms.py
from django import forms

from . import models


class TaskForm(forms.ModelForm):

	class Meta:
		model = models.Task
		fields = ['name', 'desc', 'made', 'clinic']
  
class ItemForm(forms.ModelForm):

	class Meta:
		model = models.Item
		fields = ['name', 'amount', 'used_today', 'clinic']
    
class PartnerForm(forms.ModelForm):

	class Meta:
		model = models.Partner
		fields = ['name', 'surname', 'clinic']
    
class ClientForm(forms.ModelForm):

	class Meta:
		model = models.Client
		fields = ['name', 'surname', 'isAdult', 'partner']
  

med/crm/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model

from . import forms, models

User = get_user_model()


def is_member(user):
    return user.groups.filter(name='clients').exists()


def index(request):
    if request.user:
        if request.user.is_staff:
            context = {'clinics': {}}
            for user in User.objects.all():
                if is_member(user):
                    context['clinics'][user.username] = user.first_name
            
            return render(request, 'index.html', context)
        
        return redirect(f'{request.user.username}/')

def clinic(request, pk):
    context = {}
    
    return render(request, 'clinic.html', context)

def storage(request, pk):
    if request.method == 'POST':
        form = forms.ItemForm(request.POST)
        print(form.errors)
        if form.is_valid():
            form.save()
            
    if request.GET.get('method', '') == 'delete':
        res = request.GET.get('name', '')
        if res:
            models.Item.objects.filter(name=res).delete()
            
    if request.GET.get('method', '') == 'edit':
        res_name = request.GET.get('name', '')
        res_amount = request.GET.get('amount', '')
        if res_name and res_amount:
            item = models.Item.objects.filter(name=res_name)
            if item.exists:
                item = item.first()
                item.amount = res_amount
                item.save()
    
    user = User.objects.get(username=pk)
    
    form = forms.ItemForm(initial={'clinic': user, 'used_today': 0})
    
    context = {
        'form': form,
        'clinic': pk,
    }
    
    items = models.Item.objects.filter(clinic=user)
    
    if items.exists():
        context['items'] = items.all()
        
    
    return render(request, 'storage.html', context)

def tasks(request, pk):
    
    if request.method == 'POST':
        form = forms.TaskForm(request.POST)
        print(form.errors)
        if form.is_valid():
            form.save()
            
    if request.GET.get('method', '') == 'delete':
        res = request.GET.get('name', '')
        if res:
            models.Task.objects.filter(name=res).delete()
    elif request.GET.get('method', '') == 'complete':
        res = request.GET.get('name', '')
        if res:
            task = models.Task.objects.filter(name=res).first()
            task.made = True
            task.save()
    
    user = User.objects.get(username=pk)
    
    form = forms.TaskForm(initial={'clinic': user, 'made': False})
    
    context = {
        'form': form,
        'clinic': pk,
    }
    
    tasks = models.Task.objects.filter(clinic=user)
    
    if tasks.exists():
        context['tasks'] = tasks.all()
        
    
    return render(request, 'tasks.html', context)

def partners(request, pk):
    
    if request.method == 'POST':
        form = forms.PartnerForm(request.POST)
        print(form.errors)
        if form.is_valid():
            form.save()
            
    if request.GET.get('method', '') == 'delete':
        res = request.GET.get('id', '')
        if res:
            models.Partner.objects.filter(id=res).delete()
            
    
    user = User.objects.get(username=pk)
    
    form = forms.PartnerForm(initial={'clinic': user})
    
    context = {
        'form': form,
    }
    
    clinic_partners = models.Partner.objects.filter(clinic=user)
    if clinic_partners.exists():
        context['partners'] = clinic_partners.all()
    
    return render(request, 'partners.html', context)

def clients(request, pk, id):
    
    if request.method == 'POST':
        form = forms.ClientForm(request.POST)
        print(form.errors)
        if form.is_valid():
            partner = models.Partner.objects.filter(id=id).first()
            partner.client_num += 1
            partner.save()
            form.save()
            
    if request.GET.get('method', '') == 'delete':
        res = request.GET.get('id', '')
        if res:
            client = models.Client.objects.filter(id=res)
            partner = models.Partner.objects.filter(id=id).first()
            partner.client_num -= 1
            partner.bill -= client.bill
            partner.payed -= client.payed
            partner.save()
            client.delete()
            
    if request.GET.get('method', '') == 'edit':
        res_id = request.GET.get('client_id', '')
        res_bill = request.GET.get('bill', '')
        res_payed = request.GET.get('payed', '')
        if res_id:
            client = models.Client.objects.filter(id=res_id)
            if client.exists:
                client = client.first()
                partner = models.Partner.objects.filter(id=id).first()
                if res_bill:
                    diff = client.bill - int(res_bill)
                    partner.bill -= diff
                    partner.save()
                    client.bill = res_bill
                if res_payed:
                    diff = client.payed - int(res_payed)
                    partner.payed -= diff
                    partner.save()
                    client.payed = res_payed
                client.save()
    
    form = forms.ClientForm(initial={'partner': id})
    
    context = {
        'form': form,
    }
    
    partner_clients = models.Client.objects.filter(partner=id)
    if partner_clients.exists():
        context['clients'] = partner_clients.all()
    
    return render(request, 'clients.html', context)

med/crm/templates/_base.html
<!DOCTYPE html>
<html>
  <head>
    <title>MED CRM</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">
	{% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!--<link rel="stylesheet" href="{% static 'css/index.css' %}">-->
  </head>
  <body>
    <div class="container">
      <div class="nav">
        {% if user.is_authenticated %}
          <a href="{% url 'logout'%}">Выйти</a>
        {% else %}
          <a href="{% url 'login'%}">Войти</a>
        {% endif %} 
      </div>
      {% block content %}{% endblock %}
    </div>
  </body>
</html>

med/crm/templates/clients.html
{% extends "_base.html" %} 
{% block content %}
<h1 class='card-header'>MED CRM</h1>
{% if user.is_staff or user.is_authenticated %}
<div class="container">
  <div class="row">
    <a class="card col" href="../">
      Назад
    </a>
  </div>
</div>
<div class="container">
  <form method="post" class="card-body">
    {% csrf_token %}
    <ul class="list-group list-group-flush">
      <li class="list-group-item">Имя<br>{{ form.name }}</li>
      <li class="list-group-item">Фамилия<br>{{ form.surname }}</li>
      <li class="list-group-item">Взрослый<br>{{ form.isAdult }}</li>
      {{ form.partner.as_hidden }}
      <li class="list-group-item"><button class="button" type="submit">Добавить</button></li>
    </ul>
  </form>
</div>
<div class="container">
    <table class="table">
    <thead>
        <tr>
            <th scope="col">Имя</th>
            <th scope="col">Взрослый</th>
            <th scope="col">Прибыль</th>
            <th scope="col">Долг</th>
        </tr>
    </thead>
    <tbody>

        {% for client in clients %}
            <tr>
                <td>{{ client.name }} {{ client.surname }}</td>
                <td>
                {% if client.isAdult %}
                        Да
                    {% else %}
                        Нет
                    {% endif %}
                </td>
                <form method="get" class="card-body">
                <td><input type="number" name="payed" value="{{ client.payed }}" id="id_payed"></td>
                <td><input type="number" name="bill" value="{{ client.bill }}" id="id_bill"></td>
                <input type="hidden" name="client_id" value="{{ client.id }}" id="id_id">
                <input type="hidden" name="method" value="edit">
                <td><button class="button" type="submit">Изменить</button></td>
                </form>
                <form method="get" class="card-body">
                <input type="hidden" name="id" value="{{ client.id }}" id="id_id">
                <input type="hidden" name="method" value="delete">
                <td><button class="button" type="submit">Удалить</button></td>
                </form>
            </tr>
        {% endfor %}

    </tbody>
    </table>
</div>
{% else %}
<div class='item'>
<p class='desc'>Войдите в систему, чтобы увидеть эту страницу.</p>
</div>
{% endif %} 
{% endblock %}

med/crm/templates/clinic.html
{% extends "_base.html" %} 
{% block content %}
<h1 class='card-header'>MED CRM</h1>
{% if user.is_authenticated %}
<div class="container">
  <div class="row">
    <a class="card col" href="../">
      Назад
    </a>
    <a class="card col" href="tasks/">
      Список задач
    </a>
    <a class="card col" href="storage/">
      Склад
    </a>
    <a class="card col" href="partners/">
      Партнеры
    </a>
  </div>
</div>
{% else %}
<div class='item'>
<p class='desc'>Войдите в систему, чтобы увидеть эту страницу.</p>
</div>
{% endif %} 
{% endblock %}

med/crm/templates/index.html
{% extends "_base.html" %} 
{% block content %}
<h1 class='card-header'>MED CRM</h1>
{% if user.is_staff %}
<div class="container">
  <div class="row">
    {% for key, value in clinics.items %}
    <a class="col" href="{{ key }}/">
      {{ value }}
    </a>
    {% endfor %}
  </div>
</div>
{% elif user.is_authenticated %}
<div class="testbox">
</div>
{% else %}
<div class='item'>
<p class='desc'>Войдите в систему, чтобы увидеть эту страницу.</p>
</div>
{% endif %} 
{% endblock %}

med/crm/templates/partners.html
{% extends "_base.html" %} 
{% block content %}
<h1 class='card-header'>MED CRM</h1>
{% if user.is_staff or user.is_authenticated %}
<div class="container">
  <div class="row">
    <a class="card col" href="../">
      Назад
    </a>
  </div>
</div>
<div class="container">
  <form method="post" class="card-body">
    {% csrf_token %}
    <ul class="list-group list-group-flush">
      <li class="list-group-item">Имя<br>{{ form.name }}</li>
      <li class="list-group-item">Фамилия<br>{{ form.surname }}</li>
      {{ form.clinic.as_hidden }}
      <li class="list-group-item"><button class="button" type="submit">Добавить</button></li>
    </ul>
  </form>
</div>
<div class="container">
    <table class="table">
    <thead>
        <tr>
            <th scope="col">Имя</th>
            <th scope="col">Прибыль</th>
            <th scope="col">Долг</th>
            <th scope="col">Клиенты</th>
        </tr>
    </thead>
    <tbody>

        {% for partner in partners %}
            <tr>
                <td>{{ partner.name }} {{ partner.surname }}</td>
                <td>{{ partner.payed }}</td>
                <td>{{ partner.bill }}</td>
                <td>{{ partner.client_num }}</td>
                <td><a class="button" href="{{ partner.id }}/">Подробнее</a></td>
                <form method="get" class="card-body">
                <input type="hidden" name="id" value="{{ partner.id }}" id="id_id">
                <input type="hidden" name="method" value="delete">
                <td><button class="button" type="submit">Удалить</button></td>
                </form>
            </tr>
        {% endfor %}

    </tbody>
    </table>
</div>
{% else %}
<div class='item'>
<p class='desc'>Войдите в систему, чтобы увидеть эту страницу.</p>
</div>
{% endif %} 
{% endblock %}

med/crm/templates/storage.html
{% extends "_base.html" %} 
{% block content %}
<h1 class='card-header'>MED CRM</h1>
{% if user.is_staff or user.is_authenticated %}
<div class="container">
  <div class="row">
    <a class="card col" href="../">
      Назад
    </a>
  </div>
</div>
<div class="container">
  <form method="post" class="card-body">
    {% csrf_token %}
    <ul class="list-group list-group-flush">
      <li class="list-group-item">Название<br>{{ form.name }}</li>
      <li class="list-group-item">Количество<br>{{ form.amount }}</li>
      {{ form.clinic.as_hidden }}
      {{ form.used_today.as_hidden }}
      <li class="list-group-item"><button class="button" type="submit">Добавить</button></li>
    </ul>
  </form>
</div>
<div class="container">
    <table class="table">
    <thead>
        <tr>
            <th scope="col">Название</th>
            <th scope="col">Исп. сегодня</th>
            <th scope="col">Количество</th>
        </tr>
    </thead>
    <tbody>

        {% for item in items %}
            <tr>
                <td>{{ item.name }}</td>
                <td>{{ item.used_today }}</td>
                <form method="get" class="card-body">
                <input type="hidden" name="name" value="{{ item.name }}" id="id_name">
                <input type="hidden" name="method" value="edit">
                <td><input type="number" name="amount" value="{{ item.amount }}" id="id_amount"></td>
                <td><button class="button" type="submit">Изменить</button></td>
                </form>

                <form method="get" class="card-body">
                <input type="hidden" name="name" value="{{ item.name }}" id="id_name">
                <input type="hidden" name="method" value="delete">
                <td><button class="button" type="submit">Удалить</button></td>
                </form>
                
            </tr>
        {% endfor %}

    </tbody>
    </table>
</div>
{% else %}
<div class='item'>
<p class='desc'>Войдите в систему, чтобы увидеть эту страницу.</p>
</div>
{% endif %} 
{% endblock %}

med/crm/templates/tasks.html
{% extends "_base.html" %} 
{% block content %}
<h1 class='card-header'>MED CRM</h1>
<div class="container">
  <div class="row">
    <a class="card col" href="../">
      Назад
    </a>
  </div>
</div>
{% if user.is_staff %}
<div class="container">
  <form method="post" class="card-body">
    {% csrf_token %}
    <ul class="list-group list-group-flush">
      <li class="list-group-item">Название<br>{{ form.name }}</li>
      <li class="list-group-item">Описание<br>{{ form.desc }}</li>
      {{ form.clinic.as_hidden }}
      {{ form.made.as_hidden }}
      <li class="list-group-item"><button class="button" type="submit">Добавить</button></li>
    </ul>
  </form>
</div>
{% endif %}
{% if user.is_authenticated %}
<div class="container">
    <table class="table">
    <thead>
        <tr>
            <th scope="col">Задача</th>
            <th scope="col">Описание</th>
            <th scope="col">Выполнение</th>
        </tr>
    </thead>
    <tbody>

        {% for task in tasks %}
            <tr>
                <td>{{ task.name }}</td>
                <td>{{ task.desc }}</td>
                    {% if task.made %}
                        <td class='table-success'>
                        Готово
                    {% else %}
                        <td class='table-danger'>
                        Не сделано
                    {% endif %}
                </td>
                <td>
                <form method="get" class="card-body">
                <input type="hidden" name="name" value="{{ task.name }}" id="id_name">
                {% if user.is_staff %}
                <input type="hidden" name="method" value="delete">
                <button class="button" type="submit">Удалить</button>
                {% else %}
                <input type="hidden" name="method" value="complete">
                <button class="button" type="submit">Завершить</button>
                {% endif %}
                </form>
                </td>
            </tr>
        {% endfor %}

    </tbody>
    </table>
</div>
{% else %}
<div class='item'>
<p class='desc'>Войдите в систему, чтобы увидеть эту страницу.</p>
</div>
{% endif %} 
{% endblock %}